### ISSUE TITLE
提一点建议

### ISSUE THREAD

**Issue by wcgCoding** [hawkhe/spellMatch#1]
1.由于matchString没有进行大写转换 这里一直返回false。
`if ([spellLetterString containsString:matchString] ||
        [spellString containsString:matchString]) {
`
2.进行匹配的 建议结果用数组返回，因为拼音可以匹配到很多字符串的。
“zg” 匹配 “我爱中国，这个很不错吧。” 应该 匹配到 ”中国“ 和 “这个” 。

**Comment by adduct** [comment]
> 1. 由于matchString没有进行大写转换 这里一直返回false
谢谢提醒 这个地方有逻辑问题，已经修复
第2个建议，使用数组返回多个结果。这个后续增加新的API来支持哈

**Comment by adduct** [comment]
第2个建议已经在新版本增加了。
使用spellsMatch可以返回所有匹配的字符串数组；使用spellsWithRangeValuesMatch可以返回所有匹配的字符串、对应的位置（NSRange）的数组。
